namespace net.minecraft.src
{

	public class GenLayerRiverInit : GenLayer
	{
		public GenLayerRiverInit(long par1, GenLayer par3GenLayer) : base(par1)
		{
			Parent = par3GenLayer;
		}

		/// <summary>
		/// Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
		/// amounts, or biomeList[] indices based on the particular GenLayer subclass.
		/// </summary>
		public override int[] GetInts(int par1, int par2, int par3, int par4)
		{
			int[] ai = Parent.GetInts(par1, par2, par3, par4);
			int[] ai1 = IntCache.GetIntCache(par3 * par4);

			for (int i = 0; i < par4; i++)
			{
				for (int j = 0; j < par3; j++)
				{
					InitChunkSeed(j + par1, i + par2);
					ai1[j + i * par3] = ai[j + i * par3] <= 0 ? 0 : NextInt(2) + 2;
				}
			}

			return ai1;
		}
	}

}