namespace net.minecraft.src
{

	public class GenLayerSwampRivers : GenLayer
	{
		public GenLayerSwampRivers(long par1, GenLayer par3GenLayer) : base(par1)
		{
			Parent = par3GenLayer;
		}

		/// <summary>
		/// Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
		/// amounts, or biomeList[] indices based on the particular GenLayer subclass.
		/// </summary>
		public override int[] GetInts(int par1, int par2, int par3, int par4)
		{
			int[] ai = Parent.GetInts(par1 - 1, par2 - 1, par3 + 2, par4 + 2);
			int[] ai1 = IntCache.GetIntCache(par3 * par4);

			for (int i = 0; i < par4; i++)
			{
				for (int j = 0; j < par3; j++)
				{
					InitChunkSeed(j + par1, i + par2);
					int k = ai[j + 1 + (i + 1) * (par3 + 2)];

					if (k == BiomeGenBase.Swampland.BiomeID && NextInt(6) == 0)
					{
						ai1[j + i * par3] = BiomeGenBase.River.BiomeID;
						continue;
					}

					if ((k == BiomeGenBase.Jungle.BiomeID || k == BiomeGenBase.JungleHills.BiomeID) && NextInt(8) == 0)
					{
						ai1[j + i * par3] = BiomeGenBase.River.BiomeID;
					}
					else
					{
						ai1[j + i * par3] = k;
					}
				}
			}

			return ai1;
		}
	}
}